version: '3.8'

services:
  pulseup-agent-debug:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: 1.0.1
        BUILD_DATE: ${BUILD_DATE:-}
        GIT_COMMIT: ${GIT_COMMIT:-unknown}
        ENABLE_DEBUG: "true"
    container_name: pulseup-agent-debug
    restart: "no"
    environment:
      - ENABLE_DEBUG=true
      - WEBSOCKET_URL=${WEBSOCKET_URL:-ws://host.docker.internal:3000/ws/agent_v2}
      - JOIN_TOKEN=${JOIN_TOKEN:-test-token}
      - CERT_DIR=/var/lib/pulseup/certs
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - LOG_FORMAT=text
      - CONFIG_PATH=${CONFIG_PATH:-}
      - PULSEUP_CADDY_HOST_PATH=/etc/pulseup-agent/caddy
      - DOCKER_SOCKET_PATH=${DOCKER_SOCKET_PATH:-/var/run/docker.sock}
    volumes:
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:${DOCKER_SOCKET_PATH:-/var/run/docker.sock}
      - ./certs:/var/lib/pulseup/certs
      - caddy_data:/etc/pulseup-agent/caddy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true
    ports:
      - "2347:2347"  # Supervisor debugger
      - "2346:2346"  # Worker debugger
    networks:
      - pulseup-network
    depends_on:
      - caddy

  caddy:
    image: caddy:latest
    container_name: caddy-debug
    restart: unless-stopped
    ports:
      - "${CADDY_HTTP_PORT:-8080}:80"
      - "${CADDY_HTTPS_PORT:-8443}:443"
    volumes:
      - caddy_config:/etc/caddy
      - caddy_data:/data
    networks:
      - pulseup-network

volumes:
  caddy_config:
  caddy_data:

networks:
  pulseup-network:
    driver: bridge