version: '3.8'

services:
  pulseup-agent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${AGENT_VERSION}
        BUILD_DATE: ${BUILD_DATE:-}
        GIT_COMMIT: ${GIT_COMMIT:-unknown}
        ENABLE_DEBUG: "false"
    container_name: pulseup-agent
    restart: unless-stopped
    environment:
      - WEBSOCKET_URL=${WEBSOCKET_URL:-ws://host.docker.internal:8000/ws/agent_v2}
      - JOIN_TOKEN=${JOIN_TOKEN:-test-token}
      - CERT_DIR=/var/lib/pulseup/certs
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - LOG_FORMAT=text
      - CONFIG_PATH=${CONFIG_PATH:-}
      - PULSEUP_CADDY_HOST_PATH=/etc/pulseup-agent/caddy
      - DOCKER_SOCKET_PATH=${DOCKER_SOCKET_PATH:-/var/run/docker.sock}
    volumes:
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:${DOCKER_SOCKET_PATH:-/var/run/docker.sock}
      - ./certs:/var/lib/pulseup/certs
      - caddy_data:/etc/pulseup-agent/caddy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true
    userns_mode: "host"
    networks:
      - pulseup-network
    depends_on:
      - caddy

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "${CADDY_HTTP_PORT:-8080}:80"
      - "${CADDY_HTTPS_PORT:-8443}:443"
    volumes:
      - caddy_config:/etc/caddy
      - caddy_data:/data
    networks:
      - pulseup-network
    labels:
      - pulseup.component=caddy
      - pulseup.deployment_uid=dep_pulseup_caddy
      - pulseup.lifecycle.final_name=pulseup-caddy
      - pulseup.lifecycle.version=1
      - pulseup.managed=true
      - pulseup.service_uid=svc_pulseup_caddy

volumes:
  caddy_config:
  caddy_data:

networks:
  pulseup-network:
    driver: bridge