version: '3.8'

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WEBSOCKET_URL=${WEBSOCKET_URL}
    restart: unless-stopped
    ports:
      - "5679:5679" 